In [1]:
import numpy as np
import time


In [2]:
l1 = [1,2,3]
l2 = [4,5,6]
list(zip(l1,l2)) 

[(1, 4), (2, 5), (3, 6)]

In [3]:
arr1 = np.array([1,3,4])
print(arr1)

[1 3 4]


In [4]:
arr2 = np.array([[1,2,4,5],[35,53,56,21]])
print(arr2)
arr2 = np.full((4,4),8)
print(arr2)

[[ 1  2  4  5]
 [35 53 56 21]]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [5]:
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
ujj=np.array([[2,3,53,23],[3,4,2,123]])
print(ujj)
print("Shape",ujj.shape)

[[  2   3  53  23]
 [  3   4   2 123]]
Shape (2, 4)


In [ ]:
print(arr)

In [ ]:
print(arr2)

In [20]:
arr = np.array([[2,4,5,6],[3,5,3,2]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 4)
8
2
int64


In [ ]:
arr.astype(np.float32)
print(arr.dtype)

In [12]:
arr2[0,0] = 3
print(arr2)

[[3 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
