In [23]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[22,42,12],[5,6,7],[6,89,54]])
print(arr)

[[ 1  2  3]
 [22 42 12]
 [ 5  6  7]
 [ 6 89 54]]


In [8]:
flat = arr.flatten()
print(flat)

[ 1  2  3 22 42 12  5  6  7  6 89 54]


In [12]:
print(flat[0]) # it is indexing
print(flat[0:3]) # it is slicing 

1
[1 2 3]


In [13]:
b = flat[3:7]
b[0] = 40
print(flat)

[ 1  2  3 40 42 12  5  6  7  6 89 54]


In [25]:
mask = flat> 23
print(flat[mask])

[40 42 89 54]
