In [13]:
import numpy as np

In [2]:
# Create a 3X3 array filled with random numbers and its shape.

In [3]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.shape)

(3, 3)


In [4]:
# Convert array of floats [1.1 ,2.2,3.3] into integers.

In [5]:
array = np.array([1.1 ,2.2,3.3] , dtype= float)
array_1 = array.astype (int)
print(array_1)

[1 2 3]


In [ ]:
# Use fancy indexing to extract even numbers from [1,2,3,4,5,6]

In [19]:
array = np.array([1,2,3,4,5,6])
arr = [1,3,5]
print(array[arr])

[2 4 6]


In [ ]:
# Reshape 1D array of size 9 into 3X# matrix.

In [18]:
array = np.array([1,2,3,4,5,6,7,8,9])
reshaped = array.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
