In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.sum(arr,axis=1)) # used to sum the columns
print(np.sum(arr,axis=0)) # used to sum the rows

[ 6 15 24]
[12 15 18]


In [4]:
# Indexing in multidimension array

In [5]:
print(arr[1,2]) # output : 6

6


In [6]:
a = arr[0:2, 1:3]
print(a)

[[2 3]
 [5 6]]


In [7]:
a[0,0] = 90 # used to edit the real values.
print(arr)

[[ 1 90  3]
 [ 4  5  6]
 [ 7  8  9]]


In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.astype(float)

array([[ 1., 90.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])