In [1]:
import numpy as np

In [2]:
arr = np.array([[[4,5,6],[3,3,5]],[[7,5,7],[10,54,6]]])
print(arr)

[[[ 4  5  6]
  [ 3  3  5]]

 [[ 7  5  7]
  [10 54  6]]]


In [3]:
print(arr[1,0,1:3])

[5 7]


In [4]:
print(arr[0,0,2])

6
